version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: produtosdb
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgressenha
    ports:
      - "5442:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  postgres-data:

networks:
  backend-network:
