services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: produtosdb
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgressenha
    ports:
      - "5442:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

  api:
    build:
      context: .
    container_name: api-produtos
    depends_on:
      - postgres
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/produtosdb
      SPRING_DATASOURCE_USERNAME: postgresuser
      SPRING_DATASOURCE_PASSWORD: postgressenha
    networks:
      - backend-network

volumes:
  postgres-data:

networks:
  backend-network:
